### PR TITLE
vfs: Fix the short read check in vfsWalRead

### LINKED ISSUE #432: row size limit? getting "Error: disk I/O error" from dqlite-demo
is there a row byte size limit? 

libuv=1.44.2, libraft=0.15.0, sqlite3=3.39.4, dqlite=1.11.1

running the dqlite-demo with following

# server
```
CGO_LDFLAGS_ALLOW="-Wl,-z,now" CGO_ENABLED=1 go run  dqlite-demo.go --api 127.0.0.1:8001 --db 127.0.0.1:9001 -v
```

# client

```
# base64 /dev/urandom | head -c 20000000 > file.txt
#  curl -X PUT -T "file.txt" http://127.0.0.1:8001/my-key-1
Error: disk I/O error
```

### PR DESCRIPTION
**Pull request by cole-miller**
### Problem

When trying to read a page from the WAL, we bail early with an error if there are no committed pages in `struct vfsWal`. But sometimes a transaction will want to read its own WAL frames that haven't been committed yet, and this check will prevent that if the transaction starts out with an empty WAL (because it's running right after a checkpoint, for example).

### Solution

Remove the separate check for `w->n_frame == 0` and just see whether `vfsWalFrameLookup` returns `NULL`, indicating that there's no frame at the given index. `vfsWalFrameLookup` can retrieve frames from either `w->frames` or `w->tx`.

Closes #432 

Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Comment by freeekanayaka** [comment]
> One concern I had is that if a transaction is pending on one connection, other connections should definitely not be able to read uncommitted WAL data from that transaction; vfsWalRead itself doesn't have any checks around this, before or after this change. I think it should be taken care of by each connection having to hold the appropriate locks before trying to read from the WAL -- is that right?

That's right, it's not a VFS concern. SQLite takes care of it by taking note of the highest committed WAL frame number at the time the transaction started, and never reading past it.

File: test/integration/test_cluster.c [hunk 1]
```diff
@@ -170,3 +170,31 @@ TEST(cluster, dataOnNewNode, setUp, tearDown, 0, cluster_params)
...
+
+TEST(cluster, hugeRow, setUp, tearDown, 0, NULL)
+{
+	struct fixture *f = data;
+	unsigned stmt_id;
+	unsigned last_insert_id;
+	unsigned rows_affected;
+	char *sql;
+	ssize_t n;
+size_t huge = 20000000;
```
Comment (freeekanayaka) [inline test/integration/test_cluster.c:182]: Missing indentation.

File: test/integration/test_cluster.c [hunk 2]
```diff
@@ -170,3 +170,31 @@ TEST(cluster, dataOnNewNode, setUp, tearDown, 0, cluster_params)
...
+	sql = munit_malloc(huge);
+	n = snprintf(sql, huge, "INSERT OR REPLACE INTO model (key, value) VALUES('my-key-1', '");
+	memset(sql + n, 'A', huge - n);
+	memcpy(sql + huge - 3, "')", 3);
+	PREPARE(sql, &stmt_id);
+	free(sql);
+	EXEC(stmt_id, &last_insert_id, &rows_affected);
+	/* Again */
+	EXEC(stmt_id, &last_insert_id, &rows_affected);
+	return MUNIT_OK;
```
Comment (freeekanayaka) [inline test/integration/test_cluster.c:198]: I'm a bit surprised that the there's no test failure or assertion violation because of the prepared statement above not being finalized.

But probably we have changed that behavior and now we automatically finalize leftover statements.

**Review by freeekanayaka — APPROVED** [review]

File: test/integration/test_cluster.c (hunk 2 above)
Comment (MathieuBordere) [reply test/integration/test_cluster.c:198]: They're finalized when the statement registry is closed here https://github.com/canonical/dqlite/blob/ee7a3cdb3a996fa798443b9df51391925a12b8d8/src/gateway.c#L72
